name: "videomae"
platform: "onnxruntime_onnx"
input [
    { 
        name: "pixel_values", 
        data_type: TYPE_FP32, 
        dims: [1, 16, 3, 224, 224] 
    }
]

output [
    { 
        name: "logits", 
        data_type: TYPE_FP32, 
        dims: [-1, 2] 
    }
]

instance_group [{ kind: KIND_GPU }]